import { Suggestion } from "./types";

// placeholder mock data to matching data type received from api
// TODO remove & replace with api call
export const mockData: Suggestion[]  = [
  { score: 1, word: "Mickey Mouse" },
  { score: 2, word: "Bugs Bunny" },
  { score: 3, word: "SpongeBob SquarePants" },
  { score: 4, word: "Tom" },
  { score: 5, word: "Jerry" },
  { score: 6, word: "Scooby-Doo" },
  { score: 7, word: "Donald Duck" },
  { score: 8, word: "Goofy" },
  { score: 9, word: "Homer Simpson" },
  { score: 10, word: "Bart Simpson" },
  { score: 11, word: "Popeye" },
  { score: 12, word: "Daffy Duck" },
  { score: 13, word: "Road Runner" },
  { score: 14, word: "Wile E. Coyote" },
  { score: 15, word: "Patrick Star" },
  { score: 16, word: "Shaggy Rogers" },
  { score: 17, word: "Fred Flintstone" },
  { score: 18, word: "George Jetson" },
  { score: 19, word: "Johnny Bravo" },
  { score: 20, word: "Dexter" },
  { score: 21, word: "Blossom" },
  { score: 22, word: "Bubbles" },
  { score: 23, word: "Buttercup" },
  { score: 24, word: "Rick Sanchez" },
  { score: 25, word: "Morty Smith" },
  { score: 26, word: "Stewie Griffin" },
  { score: 27, word: "Eric Cartman" },
  { score: 28, word: "Charlie Brown" },
  { score: 29, word: "Snoopy" },
  { score: 30, word: "Optimus Prime" },
  { score: 31, word: "Pikachu" },
  { score: 32, word: "Ash Ketchum" },
  { score: 33, word: "Goku" },
  { score: 34, word: "Naruto Uzumaki" },
  { score: 35, word: "Sailor Moon" },
  { score: 36, word: "Felix the Cat" },
];